swagger: "2.0"
info:
  version: "1.0.0"
  title: "Aplicacao para validacao de senhas"
servers:
  - url: "http://localhost:8080"
tags:
- name: "ValidadorSenhaController"
  description: "Recebe requisicoes para validacao de senhas"
paths:
  /validarsenha:
    post:
      summary: "Valida uma senha enviada"
      operationId: "validarSenha"
      consumes:
        - "application/json;charset=utf-8"
      produces:
        - "application/json;charset=utf-8"
      parameters:
        - in: "body"
          name: "senha"
          description: "senha"
          required: true
          schema:
            $ref: "#/definitions/Senha"
      responses:
        "200":
          description: "Senha valida ou invalida"
          schema:
            $ref: "#/definitions/SenhaValidada"
        "400":
          description: "Parametro invalido"
        "500":
          description: "Erro ao processar solicitacao"
          schema:
            $ref: "#/definitions/MensagemErro"
definitions:
  Senha:
    required:
    - "senha"
    type: "object"
    properties:
      senha:
        type: "string"
        description: "Senha a ser validada"
        minLength: 1
        maxLength: 255
  SenhaValidada:
    type: "object"
    properties:
      senhavalida:
        type: boolean
        description: "Senha valida ou invalida"
  MensagemErro:
    type: "object"
    properties:
      uuid:
        type: "string"
        description: "Identificador unico da requisicao"
        example: "372a6d92-96bc-484e-b708-a208cf1602ce"
      erro:
        type: "string"
        description: "Mensagem amigavel do erro"
        example: "Ocorreu um erro ao processar a requisicao"
